### ISSUE TITLE
Table and TOC extensions don't work out of the box

### ISSUE THREAD

**Issue by elor** [BauweBijl/bgaewiki#1]
Hello,

When installing or locally testing bgaewiki, I am unable to use the `[TOC]` definition and the markdown tables, although the responsible python files are installed under `markdown/extensions`. Other extensions may be affected as well.
The wikilinks extension seems to work.

In the [bgaewiki demo on appengine](bgaewiki.appspot.com), those features are fully available and work without a problem.

Are there additional steps that have to be performed in order to enable the mentioned extensions? I am still in the process of trying to understand how the markdown extensions work in gaewiki/bgaewiki.

Please let me know how I can help to solve this problem. Nice work by the way
### edit

local testing is performed using `dev_appserver.py bgaewiki-master` right after extracting the downloaded zip file. I then logged into localhost:8080 as an admin user, edited the page and added `[TOC]` to the beginning of the newly-created welcome page. It only shows `[TOC]` in the resulting page, instead of an actual table of contents.

Same for markdown tables.

**Comment by BauweBijl** [comment]
Hey Erik

try this:
http://bgaewiki.appspot.com/Some_features#add-this-to-your-gaewikisettings

**Comment by BauweBijl** [comment]
you could also test stuff here:
http://bgaewiki.appspot.com/Sandbox

**Comment by elor** [comment]
Yeah, it was right there on one of the 5 pages of your wiki...

Thanks, you're amazing, I feel stupid :-)
